# Generated by Django 4.1.3 on 2023-01-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition_employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='exhibition_employee',
            name='exhibition_id',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Exhibition_employee',
        ),
    ]
